---
deployment:
  tasks:
    - export DEPLOYPATH=/home/termicrack/www
    - export GIT_REPO=/home/termicrack/repositories/termicrack-web

    - mkdir -p $DEPLOYPATH/assets/css
    - cp -R $GIT_REPO/index.html $DEPLOYPATH/
    - cp -R $GIT_REPO/assets $DEPLOYPATH/