---
deployment:
  tasks:
    - export DEPLOYPATH=/home/termicrack/public_html
    - export REPOPATH=/home/termicrack/repositories/termicrack-web
    - /bin/cp ${REPOPATH}/index.html ${DEPLOYPATH}/
    - /bin/cp -r ${REPOPATH}/assets/* ${DEPLOYPATH}/assets/
    
    - rm -rf ${DEPLOYPATH}/.git ${DEPLOYPATH}/cgi-bin ${DEPLOYPATH}/.cpanel.yml