---
deployment:
  tasks:
    - export DEPLOYPATH=/home/termicrack/public_html
    - rsync -av --exclude='.git/' --exclude='cgi-bin/' --exclude='api/' --exclude='ventas/' --exclude='trabajos/' ./ $DEPLOYPATH/